### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by WonderSeven** [yanshengjia/artificial-intelligence#1]
matlab提示如下：
 function test()
 ↑
错误: 此上下文中不允许函数定义。
我不知道为什么，代码还是可以的

**Comment by yanshengjia** [comment]
你跑 genetic_algorithm.m 就行，test.m 是我当时用于测试用的，过会我把它删了

**Comment by WonderSeven** [comment]
测试代码跑不了是什么原因？在你那边测试代码能跑起来吗？

**Comment by yanshengjia** [comment]
我记得当时是能跑的，等有空我再来试一下。这个代码是两年前的，有些细节我已经不清楚了。

**Comment by WonderSeven** [comment]
我下载了原工程也是无法运行，对于你代码倒是能看懂。

**Comment by WonderSeven** [comment]
好的，麻烦啦！

**Comment by yanshengjia** [comment]
我找到原因了，是因为 plotGA 函数所在的文件的文件名被我修改了，现在我加了个 main.m，直接运行 main.m 就可以跑了，我测试过了。

**Comment by yanshengjia** [comment]
@WonderSeven 如果运行没问题了，请及时关闭这个 issue，谢谢！

**Comment by WonderSeven** [comment]
好的，已经解决，打扰了哈

**Comment by yanshengjia** [comment]
谢谢😊
